### ISSUE TITLE
Bug when (E key) is pressed at (World Map M)

### ISSUE THREAD

**Issue by Xiaoyan366** [TheTaurunti/factorio-inventoryplaceables#1]
模组「Inventory Placeables (1.0.1)」引发了无法恢复的错误。
请向模组作者反馈此错误。

Error while running event InventoryPlaceables::on_gui_opened (ID 95)
__InventoryPlaceables__/control.lua:76: attempt to get length of local 'inventory' (a nil value)
stack traceback:
	__InventoryPlaceables__/control.lua:76: in function 'get_hard_stop_index'
	__InventoryPlaceables__/control.lua:115: in function <__InventoryPlaceables__/control.lua:93>

**Comment by TheTaurunti** [comment]
Added fix in 1.0.2.

Thank you!
